### ISSUE TITLE
Installation issue with instructions from the README file

### ISSUE THREAD

**Issue by fbollon** [fevrok/laravel-translatable#41]
Hi,

Following the instructions in the README file for installing the package:

`composer require fevrok/laravel-translatable`

 I get the following error:

`[InvalidArgumentException]                                                                                                                                                             
  Could not find a matching version of package fevrok/laravel-translatable. Check the package spelling, your version constraint and that the package is available in a stability which   
  matches your minimum-stability (dev).`

If I run :

`composer require laravelarab/tarjama`

Everything is fine

Thanks for this package

**Comment by chadidi** [comment]
The first tag of this package has been released and therefore can be installed now.
